services:
  backend:
    build: ./backend/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    develop:
      watch:
        - action: sync+restart
          path: ./backend/
          target: /app/

  frontend:
    build: ./frontend/
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/

  reverse-proxy:
    image: caddy:2.10
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80

  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tests
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
